### ISSUE TITLE
请问如何使用

### ISSUE THREAD

**Issue by lee-newly** [zlking02/Emby#1]
请问这些配置该如何添加进入圈X？我尝试直接复制内容进入配置文件的重写规则中，但是不生效

**Comment by zlking02** [comment]
你问的是否是Premiere规则？是的话如下

[rewrite_remote]
https://raw.githubusercontent.com/zlking02/Emby/main/Module/Premiere/QuanX.conf, tag=Emby Premiere, update-interval=86400, enabled=true

**Comment by lee-newly** [comment]
感谢回复，确实成果啦！

**Comment by zlking02** [comment]
不客气
